SB-92-render-polyline
BFT-Smartbus/smartbus-web pull request #11
Opened 2023-01-07 03:14 UTC by henryluan95

**What does this code do?**

For Visual: Please wait and checkout ticket SB-93

. Created a polyline-decoder.js to decode and format polyline information coming from the backend.

. Created a getPolyline function in map.js (util folder) to request the polyline for a specific route. Implemented the polyline decoder to decode the response. The getPolyline function accepts one parameter which is the routeId.

. In both RouteDetailsDriver and RouteDetailsRider, implemented the getPolyline function to render out the polyline. The userId that gets passed into the function is received from useParams.

2023-01-09 06:36 UTC, yhus requested changes

2023-01-09 06:36 UTC, yhus commented on src/utils/map.js
> +    const polyline = polylineDecoder(encodedPolyline);
RE: "Right now we only need the encoded polyline string to render it on the map. We don't need the decoded list of coordinates for anything else." 

This is what I meant by that question. It seems that polylinePath still needs a list/array of coordinates?

2023-01-09 06:36 UTC, yhus commented on src/utils/polyline-decoder.js
> +export const polylineDecoder = function (str, precision) {
So this seems to be a copy and paste of the decode function in https://github.com/mapbox/polyline/blob/master/src/polyline.js

A few questions:

1.) Why not install the @mapbox/polyline library?
2.) If there's an issue with client-side compatibility, can you include the CDN hosted version instead?
3.) Alternatively, look for other libraries that provide the same functionality, e.g. https://github.com/googlemaps/js-polyline-codec
4.) If none of those are viable options, include a link to where this is sourced from, and a clear explanation of *why* it had to be copy & pasted

In general, duplicating code like this should be avoided at all cost, since you lose the direct link with the library, and must remember to manually keep it up to date. A perfect recipe for tech debt/tricky bugs for the future

2023-01-09 06:36 UTC, yhus commented on src/utils/map.js
> +    console.log("Error occured when we try to get route details");
Log the error message/exception type as well, since the current error string is not very specific?

2023-01-09 17:20 UTC, henryluan95 commented on src/utils/map.js
> +    const polyline = polylineDecoder(encodedPolyline);
Hi Scott, as far as my understanding, the Polyline component from react-google-map/api only accepts an array of lat and ln g objects in order for it to work. That is why I have to decode and reformat it before passing the path into the component.

2023-01-09 17:48 UTC, henryluan95 commented on src/utils/polyline-decoder.js
> +export const polylineDecoder = function (str, precision) {
1-2: In their README.file, it said: "Compatible with nodejs (npm install @mapbox/polyline) and the browser (copy src/polyline.js))". That's why I copied and refactored the only function that we need for the browser (client side). Please advise if I misunderstood the documentation.

3: I looked into this one before deciding which library to implement into our code base. The @mapbox/polyline has over 16.5k users while googlemaps/js-polyline-codec only has only 73.  I decided to go with @mapbox because it seems to be more reliable.

4: I will do some testing with js-polyline-codec before using this last resource.

2023-01-09 17:58 UTC, henryluan95 commented on src/utils/map.js
> +    console.log("Error occured when we try to get route details");
Updated to "console.log(`Experiencing ${err} when we try to get route details`);"

2023-01-11 04:24 UTC, yhus commented on src/utils/map.js
> +    const polyline = polylineDecoder(encodedPolyline);
Yeah, and this is why I asked originally, I was thinking that maybe we should just have the backend return the list of coordinates instead of doing all this work on the frontend.

2023-01-11 04:30 UTC, yhus commented on src/utils/polyline-decoder.js
> +export const polylineDecoder = function (str, precision) {
The star count for https://github.com/googlemaps/js-polyline-codec is a bit surprising, but since it's an official google maps repo, and seems to be pretty actively maintained, I think it's a safe choice. A lot safer than e.g. copying and pasting code, because then you break the link to the source repo.

For this specific case, it's not really a big deal, because the implementation of encoding/decoding polylines is probably not going to change much over time. 

What I'm pointing out is more that this pattern in general can be very dangerous, and is often a recipe for creating tech debt/bombs that can explode later on (for stuff that is more volatile than encoding/decoding polylines). Therefore, every time you encounter this kind of situation, you should try to exhaust all other possible solutions before copy & pasting (and if you do end up doing that because there are no alternative solutions, definitely document in detail why, and how to find the original source, e.g. direct link to repo in comments).

2023-01-11 04:34 UTC, yhus commented on src/utils/polyline-decoder.js
> +export const polylineDecoder = function (str, precision) {
Also, just an aside - The mapbox code is also pretty garbage IMHO - if you read the google maps version, their comments (describing why for each important step: https://github.com/googlemaps/js-polyline-codec/blob/main/src/index.ts#L55) makes the logic a lot easier to understand. The mapbox version just throws around a bunch of magic numbers everywhere and just "magically" makes it work. Imagine having to modify/update this implementation 😠

2023-01-11 17:22 UTC, henryluan95 commented on src/utils/map.js
> +    const polyline = polylineDecoder(encodedPolyline);
Ah got ya. That was what I wanted before working on this ticket as well. That was why I asked Dom to give me the polyline in the required format. When you said we should use Mapbox in the front-end channel because it's easier to store polylines, I thought it was directed to me. Therefore, I implemented Mapbox into the front-end code.

2023-01-11 17:25 UTC, henryluan95 commented on src/utils/polyline-decoder.js
> +export const polylineDecoder = function (str, precision) {
Okay, thank you for your advice. Let's continue our conversation in the discord channel. It seems like letting the back-end handles the encode/decode process is a much better option.

2023-01-11 19:23 UTC, yhus commented on src/utils/polyline-decoder.js
> +export const polylineDecoder = function (str, precision) {
Sounds good. I'd still recommend giving the Google maps repo a try though. If that integrated easily and you can easily call it, it's probably better than doing the work on the backend.

2023-01-11 19:39 UTC, robester0403 requested changes

2023-01-13 23:31 UTC, henryluan95 commented on src/utils/map.js
> +    const res = await apiRequest.get(`/routeDetails/${routeId}`);
Why do we need to send Polyline requests to both heartbeat and backend?

2023-01-13 23:54 UTC, henryluan95 commented on src/utils/polyline-decoder.js
> +export const polylineDecoder = function (str, precision) {
The <PolylineF> component from react-google-map/api only accept an array of lat and lng key/value pair objects. 
For example:
path = [{
lat: 18,
lng: 18,
},{
lat: 19,
lng: 19
}]

Meanwhile, the above package returns an array of lat and lng arrays [[18,18],[19,19]]. This means that after decoding, I will have to create a use another function to loop through all the arrays (The dummy polyline returns over 378 arrays) to format the data. This is why I think leaving this to the backend is a better idea. Please let me know your thought.

2023-01-14 00:16 UTC, yhus commented on src/utils/polyline-decoder.js
> +export const polylineDecoder = function (str, precision) {
Ok, gotcha. Let's discuss this in the next sprint planning? I'm not 100% sure if it makes sense to live in the backend - it really depends on how we might use the polyline in other scenarios (which I'm not sure about).

For now, just get this ticket merged, can we go ahead and use https://github.com/googlemaps/js-polyline-codec, and leave a comment saying we're considering moving this to the backend? I think you can make this transform with a .map so should be decently quick to implement?

2023-01-14 01:25 UTC, henryluan95 commented on src/utils/polyline-decoder.js
> +export const polylineDecoder = function (str, precision) {
Yes, it's easy the implement. I was just concerned about the runtime since there is so many arrays to loop through. I have just tested and implemented js-polyline-codec.

2023-01-14 01:36 UTC, henryluan95 commented on src/pages/RouteDetailsRider/RouteDetailsRider.jsx
> +    const resPolylinePath = getPolyline(routeId);
API call is a side-effect and should be used in a useEffect. I don't think useMemo can be used in this case. Please advice if I'm wrong.

2023-01-14 01:38 UTC, henryluan95 commented on src/utils/map.js
> +    const res = await apiRequest.get(`/routeDetails/${routeId}`);
Updated.

2023-01-14 22:57 UTC, yhus approved these changes

2023-01-14 22:57 UTC, yhus commented on src/utils/axios.js
> +export const getPolyline = async (routeId) => {
Nice! I would recommend moving this into a utils/map.js or utils/mapping.js file - e.g. being specific on naming

2023-01-15 23:49 UTC, henryluan95 commented on src/utils/axios.js
> +export const getPolyline = async (routeId) => {
Hey Scott, I agree. This function was originally created in utils/map.js because I wanted to keep all map functions in this file. However, I was told that by doing this would create tech debts and was advised to move it into the Axios file. Please let me know if I should move it back or not.

2023-01-16 00:18 UTC, robester0403 requested changes

2023-01-16 00:18 UTC, robester0403 commented on src/utils/axios.js
> +export const getPolyline = async (routeId) => {
The Axios request belongs in the Axios file while the rest of the map function belongs in the mapping file.

2023-01-17 15:43 UTC, robester0403 approved these changes

2023-01-17 18:15 UTC, merged