Sb 39 pings heartbeat
BFT-Smartbus/smartbus-web pull request #5
Opened 2022-12-17 21:20 UTC by henryluan95

Ticket 39:

. Created a pingHeartBeat function that creates a heartBeatData object to send to our backend. This object is hard-coded in right now because we can't call the /userDetails endpoint at the moment. The commented-out codes are there for when the /userDetails works.

This object has 6 key/value pairs: the userId and userRole from the /userDetails endpoint. The latitude, longitude and speed from the navigator.geolocation API. And the timestamp.

The pingHeartBeat function also consumes a currentPosition() function which is created to handle the asynchronous behaviour of the navigator.geolocation API. Because the pingHeartBeat function doesn't require any rerendering, this is a better way to handle it than using states.

. Created a setInterval which accepts a HEATBEAT_SPEED (current set at 2s) to get new data and send it to the backend on an interval.

. Created a utils folder with an axios.js file that sets up a custom Axios request named authRequest. This authRequest has the baseURL and headers (including a Token) baked in itself for any requests that required an access token.

2022-12-17 21:27 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
> +const USER_DETAIL_ENDPOINT = "/userDetails";
Fixed

2022-12-17 22:18 UTC, FioraDeMarco approved these changes
Nice work!

2022-12-17 22:29 UTC, StudentCZ reviewed
Unused code as comment? Is that needed?

2022-12-17 22:38 UTC, henryluan95 commented
> Unused code as comment? Is that needed?

2022-12-17 22:45 UTC, henryluan95 commented
> Unused code as comment? Is that needed?

I think it's the requirement of the ticket. It's just that we don't have the /userDetails to use at the moment. Everything will fall in place when it's there.

2022-12-18 18:23 UTC, yhus commented on src/pages/RouteDetails/RouteDetails.jsx
> +// const USER_DETAIL_ENDPOINT = "/userDetails";
Remove commented out code

2022-12-18 18:23 UTC, yhus commented on src/pages/RouteDetails/RouteDetails.jsx
> +      // const response = await authRequest.get(USER_DETAIL_ENDPOINT);
Please remove. Can replace with a TODO comment if you expect to do this work in the future

2022-12-18 18:23 UTC, yhus commented on src/pages/RouteDetails/RouteDetails.jsx
> +        userId: 1, //To be replaced with userId
Add "TODO" to front of comment

2022-12-18 18:23 UTC, yhus commented on src/pages/RouteDetails/RouteDetails.jsx
> +        timestamp: Math.floor(Date.now() / 1000),
Would recommend factoring out to it's own variable (with an easy to understand name) to make this part easier to understand

2022-12-18 18:23 UTC, yhus commented on src/utils/axios.js
> +    //'Authorization': "TOKEN"
TODO or remove

2022-12-18 18:23 UTC, yhus commented on src/pages/RouteDetails/RouteDetails.jsx
> +      navigator.geolocation.getCurrentPosition(res, rej);
What happens if the user rejects giving us permissions to access location info?

2022-12-18 18:23 UTC, yhus commented on src/pages/RouteDetails/RouteDetails.jsx
> +      console.log(err);
Console.error?

2022-12-18 18:23 UTC, yhus commented on src/pages/RouteDetails/RouteDetails.jsx
> +      console.log(err);
Also, this reminds me, we should figure out a common logging strategy. This is fine for now but ideally we'd be aware of any logs once this is deployed to users

2022-12-18 18:23 UTC, yhus commented on src/pages/RouteDetails/RouteDetails.jsx
> +    const heartBeatID = setInterval(() => {
What happens if we navigate to a different page?

2022-12-18 19:31 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
> +// const USER_DETAIL_ENDPOINT = "/userDetails";
Added TODO to the comment.

2022-12-18 19:31 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
> +      // const response = await authRequest.get(USER_DETAIL_ENDPOINT);
Added TODO to the comment.

2022-12-18 19:31 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
> +        userId: 1, //To be replaced with userId
Added TODO to the comment.

2022-12-18 19:32 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
> +        timestamp: Math.floor(Date.now() / 1000),
Made userId and userRole into variables.

2022-12-18 19:32 UTC, henryluan95 commented on src/utils/axios.js
> +    //'Authorization': "TOKEN"
Added TODO to the comment.

2022-12-18 19:33 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
> +      navigator.geolocation.getCurrentPosition(res, rej);
Added an alert to ask for permission to access the current location. This will change when all teams agree on a way to provide a common logging strategy.

2022-12-18 19:34 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
> +      console.log(err);
Added an alert to ask for permission to access the current location. This will change when all teams agree on a way to provide a common logging strategy.

2022-12-18 19:36 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
> +    const heartBeatID = setInterval(() => {
There is a clean-up function set up in the useEffect. The heartbeat will stop the moment the users change to a different page. Should it act differently?

2022-12-19 00:55 UTC, robester0403 requested changes
Good work. Added my comments. Basically ready to merge in with these small changes.

2022-12-19 00:55 UTC, robester0403 commented on src/pages/RouteDetails/RouteDetails.jsx
We should follow what Scott recommended in our meets. Code that is not used should not be in production.  

When we should use comments is maybe when we need to explain something in a large code base. However, the code is easily readable on this page so there's no real need to comment. We can remove the TODO's

2022-12-19 00:55 UTC, robester0403 commented on src/pages/RouteDetails/RouteDetails.jsx
> +      const userId = 1; //TODO: replace this with userRole === "driver" ? response.data.driver_id : response.data.rider_id
Same here for comments

2022-12-19 00:55 UTC, robester0403 commented on src/pages/RouteDetails/RouteDetails.jsx
> +      alert("Please give permission to access your current location");
Good job on this. Usually it is not great to have alerts but I think a week or so of practicing not having console logs in the code base will help us in the long run

2022-12-19 00:55 UTC, robester0403 commented on src/pages/RouteDetails/RouteDetails.jsx
> +  };
Looks great. I think we will use these map related functions a lot.  Would be a great opportunity to start another file for pure map functions in the utils folder.

Could you please export this from such a new file described above and maybe consider changing it to currentPositionData? Since then it is more semantically clear we can grab more info than position from this function.

2022-12-19 00:55 UTC, robester0403 commented on src/utils/axios.js
> +export const authRequest = axios.create({
This is an interesting one.

In the future, we will have different URL's for the web app,  HeartBeat server, and the regular server. I think we can configure EC2 to only whitelist the front end's URL address for requests going to the heartbeat server so we don't need to authenticate for heartbeat.  We can discuss with backend team and Scott on this. Might save some work,

For now can we change this name to just apiRequest?

2022-12-19 00:55 UTC, robester0403 commented on src/pages/RouteDetails/RouteDetails.jsx
> +    const heartBeatID = setInterval(() => {
This code is done correctly right now.

Note in a conversation with Scott and Dom there probably is a situation that when the driver logs into the app he should continuously still run the heartbeat to tell us where he is so that riders can get that info as well.

2022-12-19 15:29 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
Removed TODO

2022-12-19 15:29 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
> +      alert("Please give permission to access your current location");
Thank you for the confirmation. I'll leave it as an alert for now

2022-12-19 15:30 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
> +  };
I moved it into a new js file in the utils folder. I also tested to make sure everything still works properly.

2022-12-19 15:30 UTC, henryluan95 commented on src/utils/axios.js
> +export const authRequest = axios.create({
I changed it to apiRequest.

2022-12-19 15:32 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
> +    const heartBeatID = setInterval(() => {
Thank you for the confirmation. In the next sprint, we can discuss more about when the heartbeat should start and end.

2022-12-19 15:41 UTC, StudentCZ reviewed
Looks fine on my end.

2022-12-19 18:29 UTC, yhus approved these changes

2022-12-19 18:29 UTC, yhus commented on src/pages/RouteDetails/RouteDetails.jsx
> +    const heartBeatID = setInterval(() => {
Ok, I would recommend adding a TODO comment here about having to move/rework this (in a future ticket)

The heartbeat should be sent whenever the driver has the app open, regardless of page. Ideally we'd send it in the background as well, but that might be harder to do

2022-12-19 18:29 UTC, yhus commented on src/pages/RouteDetails/RouteDetails.jsx
> +        timestamp: Math.floor(Date.now() / 1000),
Hey Henry, I was referring to the timestamp calculation 😅

2022-12-19 18:29 UTC, yhus commented on src/utils/axios.js
> +const BASE_URL = "https://localhost:5000";
Move to a configuration/env file, or add TODO to address in future

2022-12-19 20:15 UTC, henryluan95 commented on src/pages/RouteDetails/RouteDetails.jsx
> +        timestamp: Math.floor(Date.now() / 1000),
Created a variable called currentTime to store the calculation.

2022-12-19 20:16 UTC, henryluan95 commented on src/utils/axios.js
> +const BASE_URL = "https://localhost:5000";
Moved BASE_URL's value into .env file.

2022-12-19 21:26 UTC, robester0403 approved these changes

2022-12-19 23:19 UTC, merged